services:
  postgres:
    image: postgres:16
    container_name: bakery_postgres
    environment:
      POSTGRES_USER: dbt
      POSTGRES_PASSWORD: dbt
      POSTGRES_DB: bakery
    ports:
      - "5433:5432"
    volumes:
      - bakery_pgdata:/var/lib/postgresql/data

volumes:
  bakery_pgdata: